// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAcqauixoLXm5BQE4s7WBiMKzmqQdznQw',
    appId: '1:580404524212:web:7ec2af95876ea588f453e1',
    messagingSenderId: '580404524212',
    projectId: 'amisadmin-f3854',
    authDomain: 'amisadmin-f3854.firebaseapp.com',
    storageBucket: 'amisadmin-f3854.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7YSrMMmzzNTlwriadw2kUoAEQUJx2T5Q',
    appId: '1:580404524212:android:7fa307acca3380b4f453e1',
    messagingSenderId: '580404524212',
    projectId: 'amisadmin-f3854',
    storageBucket: 'amisadmin-f3854.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv2ypEm7o9dyS6XzGUjTvke1X6ekV0a14',
    appId: '1:580404524212:ios:955d4494207bf3eff453e1',
    messagingSenderId: '580404524212',
    projectId: 'amisadmin-f3854',
    storageBucket: 'amisadmin-f3854.appspot.com',
    iosBundleId: 'com.example.reservation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBv2ypEm7o9dyS6XzGUjTvke1X6ekV0a14',
    appId: '1:580404524212:ios:7e28de342d1fce38f453e1',
    messagingSenderId: '580404524212',
    projectId: 'amisadmin-f3854',
    storageBucket: 'amisadmin-f3854.appspot.com',
    iosBundleId: 'com.example.reservation.RunnerTests',
  );
}
